language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-springboot-jsf' ]; then cd .. && eval "mv $currentfolder generator-springboot-jsf" && cd generator-springboot-jsf; fi
